### ISSUE TITLE
Tailscale

### ISSUE THREAD

**Issue by drewwells** [bryopsida/k8s-dev-pod#111]
Have you looked at tailscale? This would register your pod with a virtual DNS name, so you can do `ssh my-k8s-dev-pod`

**Comment by bryopsida** [comment]
I have not, I'm assuming this is it: https://tailscale.com/tailscale-ssh/, https://tailscale.com/download/linux/ubuntu-2204? I can take a look at adding that as an option. Looks like it's relatively straight forward setup to add: https://tailscale.com/kb/1185/kubernetes/

**Comment by bryopsida** [comment]
Creation of sidecar image tracked here: https://github.com/bryopsida/docker-tailscale/issues/3

**Comment by bryopsida** [comment]
Merged a update, it's off by default but can be enabled with.

`--set tailscale.enabled=true --set tailscale.authKey=<a valid ts auth key>` This will enable a tail scale user space side car that has access to the ssh service on the main container. Opted to use the `ghcr.io/tailscale/tailscale:latest` image.
